[app]
CodeName          = "玉皇大帝"
AppMode           = "debug"
SSL			          = false
Domain            = ""
AdminEmail        = ""
LogLevel          = "info"
RpcCommandMode    = false
Endpoint          = "0.0.0.0"
RpcBindPort       = 9999
HttpPort          = 8080
ReadTimeout       = 2000
WriteTimeout      = 15000

[redis]
Host              = "127.0.0.1"
Port              = 6379
Password          = ""
MaxIdle           = 100
MaxActive         = 4000
IdleTimeout       = 180
Database          = 0

[mongo]
Enable            = true
Protocol          = "mongodb"
Host              = "127.0.0.1:27017"
DefaultDb         = ""
Username          = ""
Password          = ""
ReplicaSet        = ""
ReadPreference    = ""
ConnectTimeoutMs  = 1024
SocketTimeoutMs   = 1024
ReconnectInterval = 1024
PoolSize          = 1024
BufferMaxEntries  = 1024
KeepAlive         = false
BufferCommands    = false
AutoReconnect     = false
SSL               = false
CaFilePath        = ""